package com.osrapi.models.lablord;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "die_roll", schema = "lablord")
public final class LABLORDDieRollEntity {
	/** the code. */
	@Column(name = "code")
	@JsonProperty("code")
	@NotNull
	private String				code;
	/** the die. */
	@Cascade({ CascadeType.ALL })
	@JsonProperty("die")
	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	@NotNull
	private LABLORDDieEntity	die;
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
	@Column(name = "die_roll_id")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "die_roll_seq")
	@SequenceGenerator(name = "die_roll_seq", sequenceName = "lablord.die_roll_id_seq", allocationSize = 1)
	private Long				id;
	/** the number. */
	@Column(name = "number")
	@JsonProperty("number")
	@NotNull
	private long				number;

	/** Creates a new instance of {@link LABLORDDieRollEntity}. */
	public LABLORDDieRollEntity() {
		super();
	}
	/**
	 * Gets the code.
	 * @return {@link String}
	 */
	public String getCode() {
		return code;
	}
	/**
	 * Gets the die.
	 * @return {@link LABLORDDieEntity}
	 */
	public LABLORDDieEntity getDie() {
		return die;
	}

	/**
	 * Gets the id.
	 * @return {@link Long}
	 */
	public Long getId() {
		return id;
	}
	/**
	 * Gets the number.
	 * @return {@link long}
	 */
	public long getNumber() {
		return number;
	}
	/**
	 * Sets the code.
	 * @param val the new value
	 */
	public void setCode(final String val) {
		code = val;
	}

	/**
	 * Sets the die.
	 * @param val the new value
	 */
	public void setDie(final LABLORDDieEntity val) {
		die = val;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final Long val) {
		id = val;
	}
	/**
	 * Sets the number.
	 * @param val the new value
	 */
	public void setNumber(final long val) {
		number = val;
	}

}
