package com.osrapi.models.lablord;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "character", schema = "lablord")
public final class LABLORDCharacterEntity {
	/** the armorClass. */
	@Column(name = "armor_class")
	@JsonProperty("armor_class")
	@NotNull
	private long	armorClass;
	/** the charisma. */
	@Column(name = "charisma")
	@JsonProperty("charisma")
	@NotNull
	private long	charisma;
	/** the constitution. */
	@Column(name = "constitution")
	@JsonProperty("constitution")
	@NotNull
	private long	constitution;
	/** the dexterity. */
	@Column(name = "dexterity")
	@JsonProperty("dexterity")
	@NotNull
	private long	dexterity;

	/** the experience. */
	@Column(name = "experience")
	@JsonProperty("experience")
	@NotNull
	private long	experience;
	/** the hitPoints. */
	@Column(name = "hit_points")
	@JsonProperty("hit_points")
	@NotNull
	private long	hitPoints;
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
	@Column(name = "character_id")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "character_seq")
	@SequenceGenerator(name = "character_seq", sequenceName = "lablord.character_id_seq", allocationSize = 1)
	private Long	id;

	/** the intelligence. */
	@Column(name = "intelligence")
	@JsonProperty("intelligence")
	@NotNull
	private long	intelligence;
	/** the level. */
	@Column(name = "level")
	@JsonProperty("level")
	@NotNull
	private long	level;
	/** the maxHitPoints. */
	@Column(name = "max_hit_points")
	@JsonProperty("max_hit_points")
	@NotNull
	private long	maxHitPoints;

	/** the name. */
	@Column(name = "name")
	@JsonProperty("name")
	@NotNull
	private String	name;
	/** the strength. */
	@Column(name = "strength")
	@JsonProperty("strength")
	@NotNull
	private long	strength;
	/** the wisdom. */
	@Column(name = "wisdom")
	@JsonProperty("wisdom")
	@NotNull
	private long	wisdom;

	/** Creates a new instance of {@link LABLORDCharacterEntity}. */
	public LABLORDCharacterEntity() {
		super();
	}
	/**
	 * Gets the armorClass.
	 * @return {@link long}
	 */
	public long getArmorClass() {
		return armorClass;
	}
	/**
	 * Gets the charisma.
	 * @return {@link long}
	 */
	public long getCharisma() {
		return charisma;
	}

	/**
	 * Gets the constitution.
	 * @return {@link long}
	 */
	public long getConstitution() {
		return constitution;
	}
	/**
	 * Gets the dexterity.
	 * @return {@link long}
	 */
	public long getDexterity() {
		return dexterity;
	}
	/**
	 * Gets the experience.
	 * @return {@link long}
	 */
	public long getExperience() {
		return experience;
	}

	/**
	 * Gets the hitPoints.
	 * @return {@link long}
	 */
	public long getHitPoints() {
		return hitPoints;
	}
	/**
	 * Gets the id.
	 * @return {@link Long}
	 */
	public Long getId() {
		return id;
	}
	/**
	 * Gets the intelligence.
	 * @return {@link long}
	 */
	public long getIntelligence() {
		return intelligence;
	}

	/**
	 * Gets the level.
	 * @return {@link long}
	 */
	public long getLevel() {
		return level;
	}
	/**
	 * Gets the maxHitPoints.
	 * @return {@link long}
	 */
	public long getMaxHitPoints() {
		return maxHitPoints;
	}
	/**
	 * Gets the name.
	 * @return {@link String}
	 */
	public String getName() {
		return name;
	}

	/**
	 * Gets the strength.
	 * @return {@link long}
	 */
	public long getStrength() {
		return strength;
	}
	/**
	 * Gets the wisdom.
	 * @return {@link long}
	 */
	public long getWisdom() {
		return wisdom;
	}
	/**
	 * Sets the armorClass.
	 * @param val the new value
	 */
	public void setArmorClass(final long val) {
		armorClass = val;
	}

	/**
	 * Sets the charisma.
	 * @param val the new value
	 */
	public void setCharisma(final long val) {
		charisma = val;
	}
	/**
	 * Sets the constitution.
	 * @param val the new value
	 */
	public void setConstitution(final long val) {
		constitution = val;
	}
	/**
	 * Sets the dexterity.
	 * @param val the new value
	 */
	public void setDexterity(final long val) {
		dexterity = val;
	}

	/**
	 * Sets the experience.
	 * @param val the new value
	 */
	public void setExperience(final long val) {
		experience = val;
	}
	/**
	 * Sets the hitPoints.
	 * @param val the new value
	 */
	public void setHitPoints(final long val) {
		hitPoints = val;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final Long val) {
		id = val;
	}

	/**
	 * Sets the intelligence.
	 * @param val the new value
	 */
	public void setIntelligence(final long val) {
		intelligence = val;
	}
	/**
	 * Sets the level.
	 * @param val the new value
	 */
	public void setLevel(final long val) {
		level = val;
	}
	/**
	 * Sets the maxHitPoints.
	 * @param val the new value
	 */
	public void setMaxHitPoints(final long val) {
		maxHitPoints = val;
	}

	/**
	 * Sets the name.
	 * @param val the new value
	 */
	public void setName(final String val) {
		name = val;
	}
	/**
	 * Sets the strength.
	 * @param val the new value
	 */
	public void setStrength(final long val) {
		strength = val;
	}
	/**
	 * Sets the wisdom.
	 * @param val the new value
	 */
	public void setWisdom(final long val) {
		wisdom = val;
	}

}
