package com.osrapi.models.lablord;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "armor", schema = "lablord")
public final class LABLORDArmorEntity {
	/** the ac. */
	@Column(name = "ac")
	@JsonProperty("ac")
	@NotNull
	private long					ac;
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
	@Column(name = "armor_id")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "armor_seq")
	@SequenceGenerator(name = "armor_seq", sequenceName = "lablord.armor_id_seq", allocationSize = 1)
	private Long					id;
	/** the type. */
	@Cascade({ CascadeType.ALL })
	@JsonProperty("type")
	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	@NotNull
	private LABLORDArmorTypeEntity	type;
	/** Creates a new instance of {@link LABLORDArmorEntity}. */
	public LABLORDArmorEntity() {
		super();
	}

	/**
	 * Gets the ac.
	 * @return {@link long}
	 */
	public long getAc() {
		return ac;
	}
	/**
	 * Gets the id.
	 * @return {@link Long}
	 */
	public Long getId() {
		return id;
	}
	/**
	 * Gets the type.
	 * @return {@link LABLORDArmorTypeEntity}
	 */
	public LABLORDArmorTypeEntity getType() {
		return type;
	}

	/**
	 * Sets the ac.
	 * @param val the new value
	 */
	public void setAc(final long val) {
		ac = val;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final Long val) {
		id = val;
	}
	/**
	 * Sets the type.
	 * @param val the new value
	 */
	public void setType(final LABLORDArmorTypeEntity val) {
		type = val;
	}

}
