package com.osrapi.models.lablord;

import java.util.Map;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.MapKeyColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "weapon", schema = "lablord")
public final class LABLORDWeaponEntity {
	/** the code. */
	@Column(name = "code")
	@JsonProperty("code")
	@NotNull
	private String								code;
	@ElementCollection
	@JoinTable(name = "weapon_damages_lookup", schema = "lablord", joinColumns = @JoinColumn(name = "weapon_id") , inverseJoinColumns = @JoinColumn(name = "die_roll_id") )
	@MapKeyColumn(name = "key")
	@JsonProperty("damages")
	private Map<String, LABLORDDieRollEntity>	damages;
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
	@Column(name = "weapon_id")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "weapon_seq")
	@SequenceGenerator(name = "weapon_seq", sequenceName = "lablord.weapon_id_seq", allocationSize = 1)
	private Long								id;
	/** Creates a new instance of {@link LABLORDWeaponEntity}. */
	public LABLORDWeaponEntity() {
		super();
	}

	/**
	 * Gets the code.
	 * @return {@link String}
	 */
	public String getCode() {
		return code;
	}
	/**
	 * Gets the map of damageses.
	 * @return {@link Map}<{@link LABLORDStringEntity}, {@link DieRoll}>
	 */
	public Map<String, LABLORDDieRollEntity> getDamages() {
		return damages;
	}
	/**
	 * Gets the id.
	 * @return {@link Long}
	 */
	public Long getId() {
		return id;
	}

	/**
	 * Sets the code.
	 * @param val the new value
	 */
	public void setCode(final String val) {
		code = val;
	}
	/**
	 * Sets the mapping for damageses.
	 * @param val the new value
	 */
	public void setDamages(final Map<String, LABLORDDieRollEntity> val) {
		damages = val;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final Long val) {
		id = val;
	}

}
