package com.osrapi.models.crypts_things;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "script_action", schema = "crypts_things")
public final class CRYPTS_THINGSScriptActionEntity {
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "script_action_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "script_action_seq")
    @SequenceGenerator(
            name = "script_action_seq",
            sequenceName = "crypts_things.script_action_id_seq",
            allocationSize = 1)
    private Long id;
    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String name;
    /** the type. */
    @Column(name = "type")
    @JsonProperty("type")
    @NotNull
    private String type;
    /** Creates a new instance of {@link CRYPTS_THINGSScriptActionEntity}. */
    public CRYPTS_THINGSScriptActionEntity() {
        super();
    }

    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }
    /**
     * Gets the type.
     * @return {@link String}
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }
    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }
    /**
     * Sets the type.
     * @param val the new value
     */
    public void setType(final String val) {
        type = val;
    }

}
