package com.osrapi.models.crypts_things;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "script_bundle", schema = "crypts_things")
public final class CRYPTS_THINGSScriptBundleEntity {
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "script_bundle_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "script_bundle_seq")
    @SequenceGenerator(
            name = "script_bundle_seq",
            sequenceName = "crypts_things.script_bundle_id_seq",
            allocationSize = 1)
    private Long id;
    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String name;
    /**
     * the list of {@link CRYPTS_THINGSScriptActionEntity}s associated with this
     * {@link CRYPTS_THINGSScriptBundleEntity}.
     */
    @OneToMany(targetEntity = CRYPTS_THINGSScriptActionEntity.class,
            fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinTable(name = "script_bundle_scripts_lookup", schema = "crypts_things",
            joinColumns = @JoinColumn(name = "script_bundle_id",
                    referencedColumnName = "script_bundle_id"),
            inverseJoinColumns = @JoinColumn(name = "script_action_id",
                    referencedColumnName = "script_action_id"))
    @JsonProperty("scripts")
    private List<CRYPTS_THINGSScriptActionEntity> scripts;
    /** Creates a new instance of {@link CRYPTS_THINGSScriptBundleEntity}. */
    public CRYPTS_THINGSScriptBundleEntity() {
        super();
    }

    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }
    /**
     * Gets the list of scriptss.
     * @return {@link List}<{@link CRYPTS_THINGSScriptActionEntity}>
     */
    public List<CRYPTS_THINGSScriptActionEntity> getScripts() {
        return scripts;
    }

    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }
    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }
    /**
     * Sets the list of scriptss.
     * @param val the new value
     */
    public void setScripts(final List<CRYPTS_THINGSScriptActionEntity> val) {
        scripts = val;
    }

}
