package com.osrapi.models.crypts_things;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "dice", schema = "crypts_things")
public final class CRYPTS_THINGSDiceEntity {
    /** the code. */
    @Column(name = "code")
    @JsonProperty("code")
    @NotNull
    private String code;
    /** the die. */
    @ManyToOne(targetEntity = CRYPTS_THINGSDieEntity.class,
            fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinColumn(name = "die")
    @JsonProperty("die")
    @NotNull
    private CRYPTS_THINGSDieEntity die;
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "dice_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "dice_seq")
    @SequenceGenerator(
            name = "dice_seq",
            sequenceName = "crypts_things.dice_id_seq",
            allocationSize = 1)
    private Long id;
    /** the number. */
    @Column(name = "number")
    @JsonProperty("number")
    @NotNull
    private long number;

    /** Creates a new instance of {@link CRYPTS_THINGSDiceEntity}. */
    public CRYPTS_THINGSDiceEntity() {
        super();
    }
    /**
     * Gets the code.
     * @return {@link String}
     */
    public String getCode() {
        return code;
    }
    /**
     * Gets the die.
     * @return {@link CRYPTS_THINGSDieEntity}
     */
    public CRYPTS_THINGSDieEntity getDie() {
        return die;
    }

    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Gets the number.
     * @return {@link long}
     */
    public long getNumber() {
        return number;
    }
    /**
     * Sets the code.
     * @param val the new value
     */
    public void setCode(final String val) {
        code = val;
    }

    /**
     * Sets the die.
     * @param val the new value
     */
    public void setDie(final CRYPTS_THINGSDieEntity val) {
        die = val;
    }
    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }
    /**
     * Sets the number.
     * @param val the new value
     */
    public void setNumber(final long val) {
        number = val;
    }

}
