package com.osrapi.models.wfrp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "melee_weapon", schema = "wfrp")
public final class WFRPMeleeWeaponEntity {
	/** the dmgModifier. */
	@Column(name = "dmg_modifier")
	@JsonProperty("dmg_modifier")

	private Long	dmgModifier;
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
	@Column(name = "melee_weapon_id")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "melee_weapon_seq")
	@SequenceGenerator(name = "melee_weapon_seq", sequenceName = "wfrp.melee_weapon_id_seq", allocationSize = 1)
	private Long	id;
	/** the name. */
	@Column(name = "name")
	@JsonProperty("name")
	@NotNull
	private String	name;
	/** Creates a new instance of {@link WFRPMeleeWeaponEntity}. */
	public WFRPMeleeWeaponEntity() {
		super();
	}

	/**
	 * Gets the dmgModifier.
	 * @return {@link Long}
	 */
	public Long getDmgModifier() {
		return dmgModifier;
	}
	/**
	 * Gets the id.
	 * @return {@link Long}
	 */
	public Long getId() {
		return id;
	}
	/**
	 * Gets the name.
	 * @return {@link String}
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the dmgModifier.
	 * @param val the new value
	 */
	public void setDmgModifier(final Long val) {
		dmgModifier = val;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final Long val) {
		id = val;
	}
	/**
	 * Sets the name.
	 * @param val the new value
	 */
	public void setName(final String val) {
		name = val;
	}

}
