package com.osrapi.models.wfrp;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "weapon", schema = "wfrp")
public final class WFRPWeaponEntity {
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
	@Column(name = "weapon_id")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "weapon_seq")
	@SequenceGenerator(name = "weapon_seq", sequenceName = "wfrp.weapon_id_seq", allocationSize = 1)
	private Long							id;
	/** the meleeWeaponData. */
	@Cascade({ CascadeType.ALL })
	@JsonProperty("melee_weapon_data")
	@ManyToOne(optional = false, fetch = FetchType.LAZY)

	private WFRPMeleeWeaponEntity			meleeWeaponData;
	/** the missileWeaponData. */
	@Cascade({ CascadeType.ALL })
	@JsonProperty("missile_weapon_data")
	@ManyToOne(optional = false, fetch = FetchType.LAZY)

	private WFRPMissileWeaponEntity			missileWeaponData;
	/** the name. */
	@Column(name = "name")
	@JsonProperty("name")
	@NotNull
	private String							name;

	/**
	 * the list of {@link WFRPWeaponQualityEntity}s associated with this
	 * {@link WFRPWeaponEntity}.
	 */
	@OneToMany(targetEntity = WFRPWeaponQualityEntity.class, fetch = FetchType.EAGER)
	@Fetch(FetchMode.SELECT)
	@JoinTable(name = "weapon_qualities_lookup", schema = "wfrp", joinColumns = @JoinColumn(name = "weapon_id", referencedColumnName = "weapon_id") , inverseJoinColumns = @JoinColumn(name = "weapon_quality_id", referencedColumnName = "weapon_quality_id") )
	@JsonProperty("qualities")
	private List<WFRPWeaponQualityEntity>	qualities;
	/** the twoHanded. */
	@Column(name = "two_handed")
	@JsonProperty("two_handed")
	@NotNull
	private Boolean							twoHanded;
	/** the weaponGroup. */
	@Cascade({ CascadeType.ALL })
	@JsonProperty("weapon_group")
	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	@NotNull
	private WFRPWeaponGroupEntity			weaponGroup;

	/** Creates a new instance of {@link WFRPWeaponEntity}. */
	public WFRPWeaponEntity() {
		super();
	}
	/**
	 * Gets the id.
	 * @return {@link Long}
	 */
	public Long getId() {
		return id;
	}
	/**
	 * Gets the meleeWeaponData.
	 * @return {@link WFRPMeleeWeaponEntity}
	 */
	public WFRPMeleeWeaponEntity getMeleeWeaponData() {
		return meleeWeaponData;
	}

	/**
	 * Gets the missileWeaponData.
	 * @return {@link WFRPMissileWeaponEntity}
	 */
	public WFRPMissileWeaponEntity getMissileWeaponData() {
		return missileWeaponData;
	}
	/**
	 * Gets the name.
	 * @return {@link String}
	 */
	public String getName() {
		return name;
	}
	/**
	 * Gets the list of qualitieses.
	 * @return {@link List}<{@link WFRPWeaponQualityEntity}>
	 */
	public List<WFRPWeaponQualityEntity> getQualities() {
		return qualities;
	}

	/**
	 * Gets the twoHanded.
	 * @return {@link Boolean}
	 */
	public Boolean getTwoHanded() {
		return twoHanded;
	}
	/**
	 * Gets the weaponGroup.
	 * @return {@link WFRPWeaponGroupEntity}
	 */
	public WFRPWeaponGroupEntity getWeaponGroup() {
		return weaponGroup;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final Long val) {
		id = val;
	}

	/**
	 * Sets the meleeWeaponData.
	 * @param val the new value
	 */
	public void setMeleeWeaponData(final WFRPMeleeWeaponEntity val) {
		meleeWeaponData = val;
	}
	/**
	 * Sets the missileWeaponData.
	 * @param val the new value
	 */
	public void setMissileWeaponData(final WFRPMissileWeaponEntity val) {
		missileWeaponData = val;
	}
	/**
	 * Sets the name.
	 * @param val the new value
	 */
	public void setName(final String val) {
		name = val;
	}

	/**
	 * Sets the list of qualitieses.
	 * @param val the new value
	 */
	public void setQualities(final List<WFRPWeaponQualityEntity> val) {
		qualities = val;
	}
	/**
	 * Sets the twoHanded.
	 * @param val the new value
	 */
	public void setTwoHanded(final Boolean val) {
		twoHanded = val;
	}
	/**
	 * Sets the weaponGroup.
	 * @param val the new value
	 */
	public void setWeaponGroup(final WFRPWeaponGroupEntity val) {
		weaponGroup = val;
	}

}
