package com.osrapi.models.wfrp;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "skill_choice", schema = "wfrp")
public final class WFRPSkillChoiceEntity {
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
	@Column(name = "skill_choice_id")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "skill_choice_seq")
	@SequenceGenerator(name = "skill_choice_seq", sequenceName = "wfrp.skill_choice_id_seq", allocationSize = 1)
	private Long					id;
	/** the name. */
	@Column(name = "name")
	@JsonProperty("name")
	@NotNull
	private String					name;
	/** the numToChoose. */
	@Column(name = "num_to_choose")
	@JsonProperty("num_to_choose")
	@NotNull
	private long					numToChoose;
	/**
	 * the list of {@link WFRPSkillEntity}s associated with this
	 * {@link WFRPSkillChoiceEntity}.
	 */
	@OneToMany(targetEntity = WFRPSkillEntity.class, fetch = FetchType.EAGER)
	@Fetch(FetchMode.SELECT)
	@JoinTable(name = "skill_choice_skills_lookup", schema = "wfrp", joinColumns = @JoinColumn(name = "skill_choice_id", referencedColumnName = "skill_choice_id") , inverseJoinColumns = @JoinColumn(name = "skill_id", referencedColumnName = "skill_id") )
	@JsonProperty("skills")
	private List<WFRPSkillEntity>	skills;

	/** Creates a new instance of {@link WFRPSkillChoiceEntity}. */
	public WFRPSkillChoiceEntity() {
		super();
	}
	/**
	 * Gets the id.
	 * @return {@link Long}
	 */
	public Long getId() {
		return id;
	}
	/**
	 * Gets the name.
	 * @return {@link String}
	 */
	public String getName() {
		return name;
	}

	/**
	 * Gets the numToChoose.
	 * @return {@link long}
	 */
	public long getNumToChoose() {
		return numToChoose;
	}
	/**
	 * Gets the list of skillses.
	 * @return {@link List}<{@link WFRPSkillEntity}>
	 */
	public List<WFRPSkillEntity> getSkills() {
		return skills;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final Long val) {
		id = val;
	}

	/**
	 * Sets the name.
	 * @param val the new value
	 */
	public void setName(final String val) {
		name = val;
	}
	/**
	 * Sets the numToChoose.
	 * @param val the new value
	 */
	public void setNumToChoose(final long val) {
		numToChoose = val;
	}
	/**
	 * Sets the list of skillses.
	 * @param val the new value
	 */
	public void setSkills(final List<WFRPSkillEntity> val) {
		skills = val;
	}

}
