package com.osrapi.models.wfrp;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "talent_choice", schema = "wfrp")
public final class WFRPTalentChoiceEntity {
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "talent_choice_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "talent_choice_seq")
    @SequenceGenerator(name = "talent_choice_seq",
            sequenceName = "wfrp.talent_choice_id_seq", allocationSize = 1)
    private Long id;
    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String name;
    /** the numToChoose. */
    @Column(name = "num_to_choose")
    @JsonProperty("num_to_choose")
    @NotNull
    private long numToChoose;
    /**
     * the list of {@link WFRPTalentEntity}s associated with this
     * {@link WFRPTalentChoiceEntity}.
     */
    @OneToMany(targetEntity = WFRPTalentEntity.class, fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinTable(name = "talent_choice_talents_lookup", schema = "wfrp",
            joinColumns = @JoinColumn(name = "talent_choice_id",
                    referencedColumnName = "talent_choice_id"),
            inverseJoinColumns = @JoinColumn(name = "talent_id",
                    referencedColumnName = "talent_id"))
    @JsonProperty("talents")
    private List<WFRPTalentEntity> talents;

    /** Creates a new instance of {@link WFRPTalentChoiceEntity}. */
    public WFRPTalentChoiceEntity() {
        super();
    }
    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }

    /**
     * Gets the numToChoose.
     * @return {@link long}
     */
    public long getNumToChoose() {
        return numToChoose;
    }
    /**
     * Gets the list of talentses.
     * @return {@link List}<{@link WFRPTalentEntity}>
     */
    public List<WFRPTalentEntity> getTalents() {
        return talents;
    }
    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }

    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }
    /**
     * Sets the numToChoose.
     * @param val the new value
     */
    public void setNumToChoose(final long val) {
        numToChoose = val;
    }
    /**
     * Sets the list of talentses.
     * @param val the new value
     */
    public void setTalents(final List<WFRPTalentEntity> val) {
        talents = val;
    }

}
