package com.osrapi.models.wfrp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "equipment", schema = "wfrp")
public final class WFRPEquipmentEntity {
    /** the armourData. */
    @Cascade({ CascadeType.ALL })
    @JsonProperty("armour_data")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)

    private WFRPArmourEntity armourData;
    /** the availability. */
    @Cascade({ CascadeType.ALL })
    @JsonProperty("availability")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @NotNull
    private WFRPEquipmentAvailabilityEntity availability;
    /** the costGc. */
    @Column(name = "cost_gc")
    @JsonProperty("cost_gc")

    private Long costGc;
    /** the costP. */
    @Column(name = "cost_p")
    @JsonProperty("cost_p")

    private Long costP;

    /** the costS. */
    @Column(name = "cost_s")
    @JsonProperty("cost_s")

    private Long costS;
    /** the description. */
    @Column(name = "description")
    @JsonProperty("description")
    @NotNull
    private String description;
    /** the encumbrance. */
    @Column(name = "encumbrance")
    @JsonProperty("encumbrance")
    @NotNull
    private long encumbrance;

    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "equipment_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "equipment_seq")
    @SequenceGenerator(name = "equipment_seq",
            sequenceName = "wfrp.equipment_id_seq", allocationSize = 1)
    private Long id;
    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String name;
    /** the type. */
    @Cascade({ CascadeType.ALL })
    @JsonProperty("type")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @NotNull
    private WFRPEquipmentTypeEntity type;

    /** the weaponData. */
    @Cascade({ CascadeType.ALL })
    @JsonProperty("weapon_data")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)

    private WFRPWeaponEntity weaponData;
    /** the weaponQuality. */
    @Cascade({ CascadeType.ALL })
    @JsonProperty("weapon_quality")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)

    private WFRPWeaponQualityEntity weaponQuality;
    /** Creates a new instance of {@link WFRPEquipmentEntity}. */
    public WFRPEquipmentEntity() {
        super();
    }

    /**
     * Gets the armourData.
     * @return {@link WFRPArmourEntity}
     */
    public WFRPArmourEntity getArmourData() {
        return armourData;
    }
    /**
     * Gets the availability.
     * @return {@link WFRPEquipmentAvailabilityEntity}
     */
    public WFRPEquipmentAvailabilityEntity getAvailability() {
        return availability;
    }
    /**
     * Gets the costGc.
     * @return {@link Long}
     */
    public Long getCostGc() {
        return costGc;
    }

    /**
     * Gets the costP.
     * @return {@link Long}
     */
    public Long getCostP() {
        return costP;
    }
    /**
     * Gets the costS.
     * @return {@link Long}
     */
    public Long getCostS() {
        return costS;
    }
    /**
     * Gets the description.
     * @return {@link String}
     */
    public String getDescription() {
        return description;
    }

    /**
     * Gets the encumbrance.
     * @return {@link long}
     */
    public long getEncumbrance() {
        return encumbrance;
    }
    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }

    /**
     * Gets the type.
     * @return {@link WFRPEquipmentTypeEntity}
     */
    public WFRPEquipmentTypeEntity getType() {
        return type;
    }
    /**
     * Gets the weaponData.
     * @return {@link WFRPWeaponEntity}
     */
    public WFRPWeaponEntity getWeaponData() {
        return weaponData;
    }
    /**
     * Gets the weaponQuality.
     * @return {@link WFRPWeaponQualityEntity}
     */
    public WFRPWeaponQualityEntity getWeaponQuality() {
        return weaponQuality;
    }

    /**
     * Sets the armourData.
     * @param val the new value
     */
    public void setArmourData(final WFRPArmourEntity val) {
        armourData = val;
    }
    /**
     * Sets the availability.
     * @param val the new value
     */
    public void setAvailability(final WFRPEquipmentAvailabilityEntity val) {
        availability = val;
    }
    /**
     * Sets the costGc.
     * @param val the new value
     */
    public void setCostGc(final Long val) {
        costGc = val;
    }

    /**
     * Sets the costP.
     * @param val the new value
     */
    public void setCostP(final Long val) {
        costP = val;
    }
    /**
     * Sets the costS.
     * @param val the new value
     */
    public void setCostS(final Long val) {
        costS = val;
    }
    /**
     * Sets the description.
     * @param val the new value
     */
    public void setDescription(final String val) {
        description = val;
    }

    /**
     * Sets the encumbrance.
     * @param val the new value
     */
    public void setEncumbrance(final long val) {
        encumbrance = val;
    }
    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }
    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }

    /**
     * Sets the type.
     * @param val the new value
     */
    public void setType(final WFRPEquipmentTypeEntity val) {
        type = val;
    }
    /**
     * Sets the weaponData.
     * @param val the new value
     */
    public void setWeaponData(final WFRPWeaponEntity val) {
        weaponData = val;
    }
    /**
     * Sets the weaponQuality.
     * @param val the new value
     */
    public void setWeaponQuality(final WFRPWeaponQualityEntity val) {
        weaponQuality = val;
    }

}
