package com.osrapi.models.wfrp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "sourcebook", schema = "wfrp")
public final class WFRPSourcebookEntity {
    /** the code. */
    @Column(name = "code")
    @JsonProperty("code")
    @NotNull
    private String code;
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "sourcebook_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "sourcebook_seq")
    @SequenceGenerator(name = "sourcebook_seq",
            sequenceName = "wfrp.sourcebook_id_seq", allocationSize = 1)
    private Long id;
    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String name;
    /** the owned. */
    @Column(name = "owned")
    @JsonProperty("owned")
    @NotNull
    private Boolean owned;

    /** Creates a new instance of {@link WFRPSourcebookEntity}. */
    public WFRPSourcebookEntity() {
        super();
    }
    /**
     * Gets the code.
     * @return {@link String}
     */
    public String getCode() {
        return code;
    }
    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }

    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }
    /**
     * Gets the owned.
     * @return {@link Boolean}
     */
    public Boolean getOwned() {
        return owned;
    }
    /**
     * Sets the code.
     * @param val the new value
     */
    public void setCode(final String val) {
        code = val;
    }

    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }
    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }
    /**
     * Sets the owned.
     * @param val the new value
     */
    public void setOwned(final Boolean val) {
        owned = val;
    }

}
