package com.osrapi.models.wfrp;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "race", schema = "wfrp")
public final class WFRPRaceEntity {
    /** the background. */
    @Column(name = "background")
    @JsonProperty("background")
    @NotNull
    private String background;
    /** the code. */
    @Column(name = "code")
    @JsonProperty("code")
    @NotNull
    private long code;
    /** the description. */
    @Column(name = "description")
    @JsonProperty("description")
    @NotNull
    private String description;
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "race_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "race_seq")
    @SequenceGenerator(name = "race_seq", sequenceName = "wfrp.race_id_seq",
            allocationSize = 1)
    private Long id;

    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String name;
    /**
     * the list of {@link WFRPSkillChoiceEntity}s associated with this
     * {@link WFRPRaceEntity}.
     */
    @OneToMany(targetEntity = WFRPSkillChoiceEntity.class,
            fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinTable(name = "race_skill_choices_lookup", schema = "wfrp",
            joinColumns = @JoinColumn(name = "race_id",
                    referencedColumnName = "race_id"),
            inverseJoinColumns = @JoinColumn(name = "skill_choice_id",
                    referencedColumnName = "skill_choice_id"))
    @JsonProperty("skill_choices")
    private List<WFRPSkillChoiceEntity> skillChoices;
    /**
     * the list of {@link WFRPSkillEntity}s associated with this
     * {@link WFRPRaceEntity}.
     */
    @OneToMany(targetEntity = WFRPSkillEntity.class, fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinTable(name = "race_skills_lookup", schema = "wfrp",
            joinColumns = @JoinColumn(name = "race_id",
                    referencedColumnName = "race_id"),
            inverseJoinColumns = @JoinColumn(name = "skill_id",
                    referencedColumnName = "skill_id"))
    @JsonProperty("skills")
    private List<WFRPSkillEntity> skills;

    /**
     * the list of {@link WFRPTalentChoiceEntity}s associated with this
     * {@link WFRPRaceEntity}.
     */
    @OneToMany(targetEntity = WFRPTalentChoiceEntity.class,
            fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinTable(name = "race_talent_choices_lookup", schema = "wfrp",
            joinColumns = @JoinColumn(name = "race_id",
                    referencedColumnName = "race_id"),
            inverseJoinColumns = @JoinColumn(name = "talent_choice_id",
                    referencedColumnName = "talent_choice_id"))
    @JsonProperty("talent_choices")
    private List<WFRPTalentChoiceEntity> talentChoices;
    /**
     * the list of {@link WFRPTalentEntity}s associated with this
     * {@link WFRPRaceEntity}.
     */
    @OneToMany(targetEntity = WFRPTalentEntity.class, fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinTable(name = "race_talents_lookup", schema = "wfrp",
            joinColumns = @JoinColumn(name = "race_id",
                    referencedColumnName = "race_id"),
            inverseJoinColumns = @JoinColumn(name = "talent_id",
                    referencedColumnName = "talent_id"))
    @JsonProperty("talents")
    private List<WFRPTalentEntity> talents;
    /** Creates a new instance of {@link WFRPRaceEntity}. */
    public WFRPRaceEntity() {
        super();
    }

    /**
     * Gets the background.
     * @return {@link String}
     */
    public String getBackground() {
        return background;
    }
    /**
     * Gets the code.
     * @return {@link long}
     */
    public long getCode() {
        return code;
    }
    /**
     * Gets the description.
     * @return {@link String}
     */
    public String getDescription() {
        return description;
    }

    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }
    /**
     * Gets the list of skillChoiceses.
     * @return {@link List}<{@link WFRPSkillChoiceEntity}>
     */
    public List<WFRPSkillChoiceEntity> getSkillChoices() {
        return skillChoices;
    }

    /**
     * Gets the list of skillses.
     * @return {@link List}<{@link WFRPSkillEntity}>
     */
    public List<WFRPSkillEntity> getSkills() {
        return skills;
    }
    /**
     * Gets the list of talentChoiceses.
     * @return {@link List}<{@link WFRPTalentChoiceEntity}>
     */
    public List<WFRPTalentChoiceEntity> getTalentChoices() {
        return talentChoices;
    }
    /**
     * Gets the list of talentses.
     * @return {@link List}<{@link WFRPTalentEntity}>
     */
    public List<WFRPTalentEntity> getTalents() {
        return talents;
    }

    /**
     * Sets the background.
     * @param val the new value
     */
    public void setBackground(final String val) {
        background = val;
    }
    /**
     * Sets the code.
     * @param val the new value
     */
    public void setCode(final long val) {
        code = val;
    }
    /**
     * Sets the description.
     * @param val the new value
     */
    public void setDescription(final String val) {
        description = val;
    }

    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }
    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }
    /**
     * Sets the list of skillChoiceses.
     * @param val the new value
     */
    public void setSkillChoices(final List<WFRPSkillChoiceEntity> val) {
        skillChoices = val;
    }

    /**
     * Sets the list of skillses.
     * @param val the new value
     */
    public void setSkills(final List<WFRPSkillEntity> val) {
        skills = val;
    }
    /**
     * Sets the list of talentChoiceses.
     * @param val the new value
     */
    public void setTalentChoices(final List<WFRPTalentChoiceEntity> val) {
        talentChoices = val;
    }
    /**
     * Sets the list of talentses.
     * @param val the new value
     */
    public void setTalents(final List<WFRPTalentEntity> val) {
        talents = val;
    }

}
