package com.osrapi.models.wfrp;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "skill", schema = "wfrp")
public final class WFRPSkillEntity {
    /** the characteristic. */
    @Cascade({ CascadeType.ALL })
    @JsonProperty("characteristic")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @NotNull
    private WFRPCharacteristicEntity characteristic;
    /** the description. */
    @Column(name = "description")
    @JsonProperty("description")
    @NotNull
    private String description;
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "skill_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "skill_seq")
    @SequenceGenerator(name = "skill_seq", sequenceName = "wfrp.skill_id_seq",
            allocationSize = 1)
    private Long id;
    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String name;

    /**
     * the list of {@link WFRPTalentEntity}s associated with this
     * {@link WFRPSkillEntity}.
     */
    @OneToMany(targetEntity = WFRPTalentEntity.class, fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinTable(name = "skill_talents_lookup", schema = "wfrp",
            joinColumns = @JoinColumn(name = "skill_id",
                    referencedColumnName = "skill_id"),
            inverseJoinColumns = @JoinColumn(name = "talent_id",
                    referencedColumnName = "talent_id"))
    @JsonProperty("talents")
    private List<WFRPTalentEntity> talents;
    /** the type. */
    @Cascade({ CascadeType.ALL })
    @JsonProperty("type")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @NotNull
    private WFRPSkillTypeEntity type;
    /** Creates a new instance of {@link WFRPSkillEntity}. */
    public WFRPSkillEntity() {
        super();
    }

    /**
     * Gets the characteristic.
     * @return {@link WFRPCharacteristicEntity}
     */
    public WFRPCharacteristicEntity getCharacteristic() {
        return characteristic;
    }
    /**
     * Gets the description.
     * @return {@link String}
     */
    public String getDescription() {
        return description;
    }
    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }

    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }
    /**
     * Gets the list of talentses.
     * @return {@link List}<{@link WFRPTalentEntity}>
     */
    public List<WFRPTalentEntity> getTalents() {
        return talents;
    }
    /**
     * Gets the type.
     * @return {@link WFRPSkillTypeEntity}
     */
    public WFRPSkillTypeEntity getType() {
        return type;
    }

    /**
     * Sets the characteristic.
     * @param val the new value
     */
    public void setCharacteristic(final WFRPCharacteristicEntity val) {
        characteristic = val;
    }
    /**
     * Sets the description.
     * @param val the new value
     */
    public void setDescription(final String val) {
        description = val;
    }
    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }

    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }
    /**
     * Sets the list of talentses.
     * @param val the new value
     */
    public void setTalents(final List<WFRPTalentEntity> val) {
        talents = val;
    }
    /**
     * Sets the type.
     * @param val the new value
     */
    public void setType(final WFRPSkillTypeEntity val) {
        type = val;
    }

}
