package com.osrapi.models.wfrp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "attribute", schema = "wfrp")
public final class WFRPAttributeEntity {
    /** the code. */
    @NotNull
    private String code;
    /** the description. */
    @NotNull
    private String description;
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "attribute_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    /** the isFlaw. */
    @Column(name = "is_flaw")
    @JsonProperty("is_flaw")
    @NotNull
    private Boolean isFlaw;
    /** the name. */
    @NotNull
    private String name;
    /** Creates a new instance of {@link WFRPAttributeEntity}. */
    public WFRPAttributeEntity() {
        super();
    }
    /**
     * Gets the code.
     * @return {@link String}
     */
    public String getCode() {
        return code;
    }
    /**
     * Gets the description.
     * @return {@link String}
     */
    public String getDescription() {
        return description;
    }
    /**
     * Gets the id.
     * @return the id
     */
    public long getId() {
        return id;
    }
    /**
     * Gets the isFlaw.
     * @return {@link Boolean}
     */
    public Boolean getIsFlaw() {
        return isFlaw;
    }
    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }
    /**
     * Sets the code.
     * @param val the new value
     */
    public void setCode(final String val) {
        code = val;
    }
    /**
     * Sets the description.
     * @param val the new value
     */
    public void setDescription(final String val) {
        description = val;
    }
    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final long val) {
        id = val;
    }
    /**
     * Sets the isFlaw.
     * @param val the new value
     */
    public void setIsFlaw(final Boolean val) {
        isFlaw = val;
    }
    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }
}
