package com.osrapi.models.wfrp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "missile_weapon", schema = "wfrp")
public final class WFRPMissileWeaponEntity {
    /** the dmg. */
    @Column(name = "dmg")
    @JsonProperty("dmg")

    private Long dmg;
    /** the dmgIsSb. */
    @Column(name = "dmg_is_sb")
    @JsonProperty("dmg_is_sb")
    @NotNull
    private Boolean dmgIsSb;
    /** the dmgModifier. */
    @Column(name = "dmg_modifier")
    @JsonProperty("dmg_modifier")

    private Long dmgModifier;
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "missile_weapon_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "missile_weapon_seq")
    @SequenceGenerator(name = "missile_weapon_seq",
            sequenceName = "wfrp.missile_weapon_id_seq", allocationSize = 1)
    private Long id;

    /** the longRange. */
    @Column(name = "long_range")
    @JsonProperty("long_range")

    private Long longRange;
    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String name;
    /** the reload. */
    @Cascade({ CascadeType.ALL })
    @JsonProperty("reload")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)

    private WFRPWeaponReloadEntity reload;

    /** the shortRange. */
    @Column(name = "short_range")
    @JsonProperty("short_range")

    private Long shortRange;
    /** Creates a new instance of {@link WFRPMissileWeaponEntity}. */
    public WFRPMissileWeaponEntity() {
        super();
    }
    /**
     * Gets the dmg.
     * @return {@link Long}
     */
    public Long getDmg() {
        return dmg;
    }

    /**
     * Gets the dmgIsSb.
     * @return {@link Boolean}
     */
    public Boolean getDmgIsSb() {
        return dmgIsSb;
    }
    /**
     * Gets the dmgModifier.
     * @return {@link Long}
     */
    public Long getDmgModifier() {
        return dmgModifier;
    }
    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }

    /**
     * Gets the longRange.
     * @return {@link Long}
     */
    public Long getLongRange() {
        return longRange;
    }
    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }
    /**
     * Gets the reload.
     * @return {@link WFRPWeaponReloadEntity}
     */
    public WFRPWeaponReloadEntity getReload() {
        return reload;
    }

    /**
     * Gets the shortRange.
     * @return {@link Long}
     */
    public Long getShortRange() {
        return shortRange;
    }
    /**
     * Sets the dmg.
     * @param val the new value
     */
    public void setDmg(final Long val) {
        dmg = val;
    }
    /**
     * Sets the dmgIsSb.
     * @param val the new value
     */
    public void setDmgIsSb(final Boolean val) {
        dmgIsSb = val;
    }

    /**
     * Sets the dmgModifier.
     * @param val the new value
     */
    public void setDmgModifier(final Long val) {
        dmgModifier = val;
    }
    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }
    /**
     * Sets the longRange.
     * @param val the new value
     */
    public void setLongRange(final Long val) {
        longRange = val;
    }

    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }
    /**
     * Sets the reload.
     * @param val the new value
     */
    public void setReload(final WFRPWeaponReloadEntity val) {
        reload = val;
    }
    /**
     * Sets the shortRange.
     * @param val the new value
     */
    public void setShortRange(final Long val) {
        shortRange = val;
    }

}
