package com.osrapi.models.ff;

import java.util.Map;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.MapKeyColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "io_equip_item", schema = "ff")
public final class FFIoEquipItemEntity {
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
	@Column(name = "io_equip_item_id")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "io_equip_item_seq")
	@SequenceGenerator(name = "io_equip_item_seq", sequenceName = "ff.io_equip_item_id_seq", allocationSize = 1)
	private Long										id;
	/** the mapping for modifierss. */
	@ElementCollection
	@JoinTable(name = "io_equip_item_modifiers_lookup", schema = "ff", joinColumns = @JoinColumn(name = "io_equip_item_id") , inverseJoinColumns = @JoinColumn(name = "value_entity_table>_id") )
	@MapKeyColumn(name = "key")
	@JsonProperty("modifiers")
	private Map<String, FFEquipmentItemModifierEntity>	modifiers;
	/** Creates a new instance of {@link FFIoEquipItemEntity}. */
	public FFIoEquipItemEntity() {
		super();
	}
	/**
	 * Gets the id.
	 * @return {@link Long}
	 */
	public Long getId() {
		return id;
	}

	/**
	 * Gets the map of modifierss.
	 * @return {@link Map}<{@link String}, {@link FFEquipmentItemModifierEntity}
	 *         >
	 */
	public Map<String, FFEquipmentItemModifierEntity> getModifiers() {
		return modifiers;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final Long val) {
		id = val;
	}
	/**
	 * Sets the mapping for modifierss.
	 * @param val the new value
	 */
	public void setModifiers(
			final Map<String, FFEquipmentItemModifierEntity> val) {
		modifiers = val;
	}

}
